---
# tasks file for database
- name: Install MariaDB
  ansible.builtin.dnf:
    name: mariadb-server
    state: present
  notify: Start MariaDB

- name: Ensure MariaDB is running
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  register: mariadb_service
  when: mariadb_service is not defined or mariadb_service is changed
  notify: Start MariaDB

- name: Install PyMySQL for Python
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3

- name: Set root password (if new install)
  ansible.builtin.command: >
    mysqladmin -u root password "{{ mysql_root_password }}"
  ignore_errors: yes
  register: set_root_password
  when: set_root_password is not defined or set_root_password is changed

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  register: create_db
  when: create_db is not defined or create_db is changed

- name: Create WordPress user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  register: create_user
  when: create_user is not defined or create_user is changed
  notify: Restart MariaDB

  