---
# handlers file for database

- name: Start MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  
- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: yes
  