---
- name: List buckets
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: List Buckets
      oci_object_storage_bucket_facts:
        namespace_name: oraxxxx
        compartment_id: "ocid1.compartment.oc1..xxxxxxEXAMPLExxxxxx"
        auth_type: "api_key"
        region: "us-phoenix-1"
      register: result

    - name: Show bucket names
      debug:
        msg: "{{ item.name }}"
      loop: "{{ result.buckets }}"

