- name: Launch Compute Instance
  hosts: localhost
  gather_facts: no
  collections:
    - oracle.oci
  vars_files:
    - "../group_vars/all.yml"
  tasks:
    - name: Launch compute instance
      oci_compute_instance:
        compartment_id: "{{ compartment_ocid }}"
        availability_domain: "{{ availability_domain }}"
        display_name: "TrainingInstance-{{ '%02d' | format(item) }}"
        shape: "{{ shape }}"
        shape_config:
          ocpus: 1
          memory_in_gbs: 6
        subnet_id: "{{ subnet_ocid }}"
        source_details:
          source_type: image
          image_id: "{{ image_ocid }}"
        metadata:
          ssh_authorized_keys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      loop: "{{ range(1, 6) | list }}"
      async: 600
      poll: 0
      register: instance_result

    - debug: var=instance_result

