---
# handlers file for roles/webserver

- name: restart apache
  service:
    name: apache2
    state: restarted
  become: yes
  
- name: Reload firewalld to apply changes
  command: firewall-cmd --reload
  become: yes