---
# tasks file for roles/database

- name: Install MariaDB server
  ansible.builtin.dnf:
    name: mariadb-server
    state: present
    update_cache: yes
  become: yes

- name: Install PyMySQL for Python 3
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3
  become: yes

- name: Ensure MySQL is running
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  become: yes

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  become: yes

- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    state: present
  become: yes
