---
- name: Test WinRM connection
  hosts: windows
  gather_facts: no
  tasks:
    - name: Get uptime from Windows
      ansible.windows.win_shell: |
        systeminfo | findstr "System Boot Time"
      register: result

    - name: Show uptime result
      ansible.builtin.debug:
        var: result.stdout


- name: Install and Enable IIS server on windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_management_tools: yes  # Ensures tools like IIS Manager are installed
      register: iis_install

    - name: Reboot if IIS installation requires it
      ansible.windows.win_reboot:
      when: iis_install.reboot_required

    - name: Start IIS service
      ansible.windows.win_service:
        name: W3SVC
        state: started

    - name: Enable IIS service to start on boot
      ansible.windows.win_service:
        name: W3SVC
        start_mode: auto

    - name: Check if IIS is running
      ansible.windows.win_shell: |
        (Get-Service W3SVC).Status
      register: iis_status

    - name: Show IIS status result
      ansible.builtin.debug:
        var: iis_status.stdout


- name: Open firewall for HTTP and HTTPS
  hosts: windows
  gather_facts: no
  tasks:
    - name: Open HTTP port
      community.windows.win_firewall_rule:
        name: Allow HTTP for IIS
        localport: 80
        protocol: TCP
        direction: in
        action: allow
        state: present
        enable: yes

    - name: Open HTTPS port
      community.windows.win_firewall_rule:
        name: Allow HTTPS for IIS
        localport: 443
        protocol: TCP
        direction: in
        action: allow
        state: present
        enable: yes

    - name: Check if firewall rules were created successfully
      ansible.windows.win_shell: |
        Get-NetFirewallRule -DisplayName "Allow HTTP for IIS", "Allow HTTPS for IIS"
      register: firewall_rules

    - name: Show firewall rule creation result
      ansible.builtin.debug:
        var: firewall_rules.stdout