- name: Write a template to the IIS default directory
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Create a simple HTML file
      ansible.windows.win_template:
        src: templates/index.html.j2
        dest: C:\inetpub\wwwroot\index.html

    - name: Check if the file was created successfully
      ansible.windows.win_shell: |
        Get-ChildItem C:\inetpub\wwwroot\index.html
      register: result

    - name: Show file creation result
      ansible.builtin.debug:
        var: result.stdout