---
# defaults file for roles/wordpress

wp_version: "6.0.2"
wp_install_dir: "/var/www/html"
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: securepassword
wp_db_host: localhost
wp_table_prefix: wp_
wp_debug: false
