---
# tasks file for roles/webserver

- name: Install Apache (httpd) on Oracle Linux 8
  ansible.builtin.dnf:
    name: httpd
    state: present
    update_cache: yes
  become: yes

- name: Ensure Apache is running and enabled
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
  become: yes

- name: Open HTTP port (80/tcp) in the firewall
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled
  become: yes

- name: Open HTTPS port (443/tcp) in the firewall
  ansible.posix.firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled
  become: yes

- name: Set SELinux boolean to allow Apache to connect to the network
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: yes
  become: yes
  notify: 
    - restart apache
    - Reload firewalld to apply changes
