---
# tasks file for roles/wordpress

- name: Install PHP and dependencies
  ansible.builtin.dnf:
    name:
      - php
      - php-mysqlnd
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
    state: present
  become: yes

- name: Create web root directory
  ansible.builtin.file:
    path: "{{ wp_install_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'
  become: yes

- name: Download WordPress
  ansible.builtin.get_url:
    url: "https://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
    dest: "/tmp/wordpress-{{ wp_version }}.tar.gz"
  become: yes

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: "/tmp/wordpress-{{ wp_version }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
  become: yes

- name: Move WordPress files
  ansible.builtin.shell: "cp -a /tmp/wordpress/. {{ wp_install_dir }}/"
  become: yes

- name: Set ownership
  ansible.builtin.file:
    path: "{{ wp_install_dir }}"
    owner: apache
    group: apache
    recurse: yes
  become: yes

- name: Create wp-config.php
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wp_install_dir }}/wp-config.php"
    owner: apache
    group: apache
  become: yes

- name: Ensure policycoreutils-python-utils is installed (required for semanage)
  ansible.builtin.dnf:
    name: policycoreutils-python-utils
    state: present
  become: yes

- name: Set SELinux httpd_sys_content_t context for WordPress directory
  community.general.sefcontext:
    target: "{{ wp_install_dir }}"
    setype: httpd_sys_content_t
    state: present
  become: yes

- name: Restore SELinux context on WordPress directory
  ansible.builtin.command: restorecon -Rv /var/www/html
  become: yes
  notify: restart apache

- name: Display last 100 lines of PHP error log
  command: tail -100 /var/log/httpd/error.log
  register: php_errors
- debug:
    var: php_errors.stdout_lines

- name: Restart Apache
  ansible.builtin.service:
    name: httpd
    state: restarted
  become: yes